name: Issues

on: 
  issues:
    types: [opened]
    branches:
      - master


jobs:
  issues-data:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Issues data 
        run: echo "${{ toJSON(github) }}"
